version: v1.0.0

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

dsn: postgres://kratos:secret@postgres:5432/kratos?sslmode=disable

identity:
  schemas:
    - id: default
      url: file:///etc/config/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://foo:bar@my-mailserver:1234/?skip_ssl_verify=false

selfservice:
  default_browser_return_url: http://localhost:4455/

  flows:
    login:
      ui_url: http://localhost:4455/login
      lifespan: 10m
    registration:
      ui_url: http://localhost:4455/registration
      lifespan: 10m
    recovery:
      enabled: true
      ui_url: http://localhost:4455/recovery
    verification:
      enabled: true
      ui_url: http://localhost:4455/verification
    settings:
      ui_url: http://localhost:4455/settings
      lifespan: 10m

  methods:
    password:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
